version: '3'
services:
  not_gate:
    build: .
    command: not -listen-addr '0.0.0.0:8080' -output-addrs 'http://and_gate:8080/input/a'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8080:8080
  or_gate:
    build: .
    command: or -listen-addr '0.0.0.0:8080' -output-addrs 'http://and_gate:8080/input/b'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8081:8080
  and_gate:
    build: .
    command: and -listen-addr '0.0.0.0:8080'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8082:8080
  xor_gate:
    build: .
    command: xor -listen-addr '0.0.0.0:8080'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8083:8080
  nand_gate:
    build: .
    command: nand -listen-addr 0.0.0.0:8080 -output-addrs 'http://xor_gate:8080/input/a,http://xor_gate:8080/input/b'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8084:8080
  nor_gate:
    build: .
    command: nor listen-addr '0.0.0.0:8080'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8085:8080
