version: '3'
services:
  and_gate:
    build: .
    command: and -listen-addr '0.0.0.0:8080'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
  xor_gate:
    build: .
    command: xor -listen-addr '0.0.0.0:8080'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
  input:
    build: .
    entrypoint: >
      /bin/bash -c "for TICK in {0..1024}; do curl -X POST -s -d '{\"state\": true, \"tick\":'$$TICK'}' http://{xor_gate,and_gate}:8080/input/{a,b} && sleep 1; done"
    depends_on:
      xor_gate:
        condition: service_healthy
      and_gate:
        condition: service_healthy
