version: '3'
services:
  not_gate:
    build: .
    environment:
      LISTEN_ADDR: "0.0.0.0:8080"
      SERVICE_TYPE: not
      OUTPUT_TYPE: http
      OUTPUT_ADDRS: 'http://and_gate:8080/input/a'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8080:8080
  or_gate:
    build: .
    environment:
      LISTEN_ADDR: "0.0.0.0:8080"
      SERVICE_TYPE: or
      OUTPUT_TYPE: http
      OUTPUT_ADDRS: 'http://and_gate:8080/input/b'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8081:8080
  and_gate:
    build: .
    environment:
      LISTEN_ADDR: "0.0.0.0:80"
      SERVICE_TYPE: and
      OUTPUT_TYPE: stdout
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8082:8080
  xor_gate:
    build: .
    environment:
      LISTEN_ADDR: "0.0.0.0:80"
      SERVICE_TYPE: xor
      OUTPUT_TYPE: stdout
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:8080/healthcheck"
        ]
    ports:
      - 8083:8080
